### ISSUE TITLE
Acerca de la primera implementación

### ISSUE THREAD

**Issue by JGonz0** [Damorgal/Tarea-09#2]
Por el momento, para definir las funciones size, isEmpty, contains y get, aplicadas a los árboles rojo-negros,  se hizo un prototipo de la función put(); en esta solamente se agregan nodos como en un árbol de búsqueda binario normal. Se deben hacer las rotaciones y el recoloramiento. Si hay algo que no te parece, puedes cambiar las definiciones o la estructura del árbol. 

Por default asumí que si la llave de un nodo es 0, se trata de un nodo vacío. Podrás notar que en la función de put() se generan nuevos nodos a la izquierda y a la derecha del nodo recién creado, estos representan los nodos terminales, además de que se asigna el padre de estos.

Si hay dudas o notas alguna inconsistencia en el código, por favor házmelo saber.

**Comment by Damorgal** [comment]
Cambié lo de la llave 0, porque puede causar problemas. Básicamente, si el nodo que le pasamos al principio es vacío, se crea el nodo. Si no es vació, prosigue con la inserción como si fuera un BST normal. También quité lo de pedirle memoria a los hijos puesto que por el momento son nulos, solo se crea memoria para ellos cuando van a insertar.

**Comment by JGonz0** [comment]
De acuerdo, me parecieron bien los cambios :+1:
